recipe/urls.py
from django.urls import path
from . import views


urlpatterns = [
     path('', views.MainPage.as_view(), name='main'),
     path('decline/', views.DeclinePage.as_view(), name='decline'),
     path('home/', views.HomePage.as_view(), name='home'),
     path('about/', views.About.as_view(), name='about'),
     path('recipelist/', views.RecipesList.as_view(), name='recipes'),
     path('myrecipes/', views.MyRecipes.as_view(), name='myrecipes'),
     path('recipecreate/', views.RecipeCreate.as_view(), name='recipecreate'),
     path('recipeedit/<slug:slug>', views.RecipeEdit.as_view(),
          name='recipeedit'),
     path('recipedelete/<slug:slug>', views.RecipeDelete.as_view(),
          name='recipedelete'),
     path('<slug:slug>/', views.RecipeDetail.as_view(), name='recipe_detail'),
     path('cheers/<slug:slug>', views.RecipeCheers.as_view(),
          name='recipe_cheers'),
]

thetipsytiger/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('recipe.urls'), name='recipe_urls'),
    path('accounts/', include('allauth.urls')),

]

handler404 = 'thetipsytiger.views.handler404'
handler500 = 'thetipsytiger.views.handler500'

recipe/models.py
"""
Imports
"""
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.text import slugify
from cloudinary.models import CloudinaryField

STATUS = ((0, 'Draft'), (1, 'published'))


class Recipe(models.Model):
    """ Model for recipe """
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="recipe_post")
    created_on = models.DateTimeField(auto_now_add=True)
    update_on = models.DateTimeField(auto_now_add=True)
    about = models.TextField(blank=True)
    ingredients = models.TextField(blank=False)
    steps = models.TextField(blank=False)
    serves = models.PositiveIntegerField(
        default=1,
        validators=[
            MinValueValidator(1),
            MaxValueValidator(4)])
    status = models.IntegerField(choices=STATUS, default=0)
    recipe_image = CloudinaryField('image', default='placeholder')
    cheers = models.ManyToManyField(
        User, related_name='recipe_cheers', blank=True)

    OPTIONS = "Options..."
    EASY = 'Quick & Easy'
    MEDIUM = 'A bit Flashy'
    HARD = 'Challenge me'

    SKILL_LEVEL = [
        (OPTIONS, 'Options...'),
        (EASY, 'Quick & Easy'),
        (MEDIUM, 'A bit Flashy'),
        (HARD, 'Challenge Me')
    ]

    skill = models.CharField(
        max_length=15,
        choices=SKILL_LEVEL,
        blank=False,
        default=OPTIONS
        )
    OPTIONS = "Options..."
    BOURBON = 'Bourbon-base'
    GIN = 'Gin-base'
    LIQUEUR = 'Liqueur-base'
    NONALCOHOLIC = 'Non-Alcoholic'
    RUM = 'Rum-base'
    TEQUILA = 'Tequila-base'
    VODKA = 'Vodka-base'
    WHISKEY = 'Whiskey-base'

    ALCOHOL_BASE_CHOICES = [
        (OPTIONS, 'Options...'),
        (BOURBON, 'Bourbon-base'),
        (GIN, 'Gin-base'),
        (LIQUEUR, 'Liqueur-base'),
        (NONALCOHOLIC, 'Non-Alcoholic'),
        (RUM, 'Rum-base'),
        (TEQUILA, 'Tequila-base'),
        (VODKA, 'Vodka-base'),
        (WHISKEY, 'Whiskey-base')
    ]

    base = models.CharField(
        max_length=15,
        choices=ALCOHOL_BASE_CHOICES,
        blank=False,
        default=OPTIONS
        )

    class Meta:
        """ Recipes ordered to show newest first """
        ordering = ['-created_on']

    def __str__(self):
        return str(self.title)

    def number_of_cheers(self):
        """ Show number of likes on a recipe """
        return self.cheers.count()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Recipe, self).save(*args, **kwargs)


class Comment(models.Model):
    """ Model for comments, for registered users """
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name='comments')
    name = models.CharField(max_length=100)
    email = models.EmailField(default=None)
    body = models.TextField(blank=False)
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        """ Comments ordered from last to first """
        ordering = ['created_on']

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

recipe/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    """comment form for logged in users"""
    class Meta:
        model = Comment
        fields = ('body',)

recipe/views.py
# pylint: disable=locally-disabled, no-member

"""Imports"""
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic, View
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Recipe
from .filters import RecipeFilter
from .forms import CommentForm


class MainPage(generic.ListView):
    """Displays home page for site"""
    model = Recipe
    template_name = 'main.html'


class DeclinePage(generic.TemplateView):
    """Displays main page for site"""
    template_name = 'decline.html'


class HomePage(generic.ListView):
    """Displays home page for site"""
    model = Recipe
    queryset = Recipe.objects.filter(status=1).order_by('-created_on')[0:3]
    template_name = 'index.html'
    paginate_by = 4


class About(generic.TemplateView):
    """Displays information about the site"""
    template_name = 'about.html'


class RecipeDetail(LoginRequiredMixin, View):
    """Displays the full cocktail recipe to logged in users"""

    def get(self, request, slug, *args, **kwargs):
        queryset = Recipe.objects.filter(status=1)
        recipe = get_object_or_404(queryset, slug=slug)
        comments = recipe.comments.filter(approved=True).order_by('created_on')
        cheers = False
        if recipe.cheers.filter(id=self.request.user.id).exists():
            cheers = True

        return render(
            request,
            "recipe_detail.html",
            {
                "recipe": recipe,
                "comments": comments,
                "commented": False,
                "cheers": cheers,
                "comment_form": CommentForm()
            }
        )

    def post(self, request, slug, *args, **kwargs):
        """shows full recipe with approved comments
        show if logged in user has given a cheers
        User can submit recipe for review to admin"""

        queryset = Recipe.objects.filter(status=1)
        recipe = get_object_or_404(queryset, slug=slug)
        comments = recipe.comments.filter(approved=True).order_by('created_on')
        cheers = False
        if recipe.cheers.filter(id=self.request.user.id).exists():
            cheers = True

        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.recipe = recipe
            comment.save()
            messages.success(request, 'Thanks for your thoughts')
        else:
            comment_form = CommentForm()

        return render(
            request,
            'recipe_detail.html',
            {
                "recipe": recipe,
                "comments": comments,
                "commented": True,
                "cheers": cheers,
                "comment_form": CommentForm()

            },
            )


class RecipesList(generic.ListView):
    """Displays view of all recipes """
    model = Recipe
    queryset = Recipe.objects.filter(status=1).order_by('-created_on')
    template_name = 'recipes.html'

    def get_queryset(self):
        """filter cocktial by skill level and alcohol base"""
        queryset = super().get_queryset()
        filter = RecipeFilter(self.request.GET, queryset)
        return filter.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        filter = RecipeFilter(self.request.GET, queryset)
        context["RecipeFilter"] = filter
        return context


class MyRecipes(LoginRequiredMixin, generic.ListView):
    """Displays logged in Users Recipes"""
    model = Recipe
    queryset = Recipe.objects.filter(status=1).order_by('-created_on')
    template_name = 'myrecipes.html'
    context_object_name = 'recipe'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['recipe'] = context['recipe'].filter(author=self.request.user)

        return context


class RecipeCheers(LoginRequiredMixin, View):
    """ Logged in Users can cheer/like a cocktial"""

    def post(self, request, slug, *args, **kwargs):
        recipe = get_object_or_404(Recipe, slug=slug)
        if recipe.cheers.filter(id=self.request.user.id).exists():
            recipe.cheers.remove(request.user)
            messages.info(request, 'You have removed your cocktail cheer!')
        else:
            recipe.cheers.add(request.user)
            messages.success(request, 'You gave this cocktail a cheers!')

        return HttpResponseRedirect(reverse('recipe_detail', args=[slug]))


class RecipeCreate(
                    SuccessMessageMixin, LoginRequiredMixin,
                    generic.CreateView):
    """Logged in user can create a recipe and add it to their cocktail list"""

    model = Recipe
    fields = ['recipe_image', 'title', 'about', 'skill', 'base', 'serves',
              'ingredients', 'steps']
    template_name = 'recipe_form.html'
    success_url = reverse_lazy('myrecipes')
    success_message = "You have added a new cocktail to your list!"

    def form_valid(self, form):
        """Places logged in users as author and sets form to publish"""
        form.instance.author = self.request.user
        form.instance.status = 1

        return super(RecipeCreate, self).form_valid(form)


class RecipeEdit(SuccessMessageMixin, LoginRequiredMixin, generic.UpdateView):
    """ Logged in User can edit the cocktail recipe"""
    model = Recipe
    fields = ['recipe_image', 'title', 'skill', 'base', 'serves', 'about',
              'ingredients', 'steps', ]
    template_name = 'recipe_form.html'
    success_url = reverse_lazy('myrecipes')
    success_message = "You have Edited your cocktail!"


class RecipeDelete(SuccessMessageMixin, LoginRequiredMixin,
                   generic.DeleteView):
    """
    Logged in user can delete a recipe from their my recipes list
    """
    model = Recipe
    success_url = reverse_lazy('myrecipes')
    success_message = "Cocktail deleted!"

    def delete(self, request, *args, **kwargs):
        messages.warning(self.request, self.success_message)
        return super(RecipeDelete, self).delete(request, *args, **kwargs)

templates/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-6 about-image-container">
            <img src="https://res.cloudinary.com/ddgxxa2hy/image/upload/v1662238765/rinck-content-studio-6YkD2qD86lg-unsplash_1_pzm1in_1_x4mv0j.jpg"
                alt="three cocktail glasses" class="about-image img-fluid">
        </div>
        <div class="col-12 col-md-6 about-text justify-content-center">
            <h3>About Us</h3>
            <p> Here at the Tipsy Tiger Cocktail Guide, we strive to bring people together over the love of
                cocktails.
                We started as a group of friends that got together every friday to celebrate the end of the working
                week.
                So during Covid lockdown as everyone's social activities were put on hold and we stayed all bundled up
                safe at home,
                our socialization platform as friends changed but we still continued to celebrate the end of the week.
                After a Few friday's, lots of cocktail trial and errors and zoom calls, The Tipsy Tiger Cocktail Guide
                was born.
            </p>
            <p>Our mission is to bring this small coummunity of together over our mutual love of cocktails and
                socializing with friends.
                <p>So come and Join us <a class="nav-tab " href="{% url 'account_signup' %}">Register</a> if you haven't
                    yet.</p>
                <p>By registering you can view <a class="nav-tab " href="{% url 'recipes' %}">Cocktails</a>
                    in greater detail.</p>
                <p>If you have registered with us <a class="nav-tab " href="{% url 'account_login' %}">Login</a> and
                    post your own favourite cocktails.</p>
                <p> Once registered You can comment on any recipe letting you know your thoughts.</p>
                <p>Oh and don't forget to give our recipes a cheer <i class="fas fa-glass-cheers"
                        aria-hidden="true"></i>The Tipsy Tiger version of a like.</p>

        </div>
    </div>
</div>


{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The Tipsy Tiger Cocktail Guide</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Special+Elite&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Itim&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body class="d-flex flex-column min-vh-100 main-bg">

    <!-- Navigation -->

    <nav class="navbar navbar-expand-lg navbar-light sticky-top bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="https://res.cloudinary.com/ddgxxa2hy/image/upload/v1660745500/My_project-1_18_qdqbdv.png"
                    alt="Tiger and cocktail glass" width="200" height="120">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == 'home' %}active{% endif %}"
                            href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if '/about/' in request.path %}active{% endif %}"
                            href="{% url 'about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if '/recipes/' in request.path %}active{% endif %}"
                            href="{% url 'recipes' %}">Cocktails</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link {% if '/myrecipes/' in request.path %}active{% endif %}"
                            href="{% url 'myrecipes' %}">My cocktails</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}

                </ul>

            </div>
        </div>
    </nav>


    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>

    <main>

        {% block content %}
        <!-- Content -->
        {% endblock %}

    </main>


    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
        <p class="m-0 text-center fun">Our cocktails are fun, & oh so Yum, But Please drink Responsibly!</p>
        <p class="m-0 text-center">&#169; Charte 2022</p>
        <p class="m-0 text-center">Follow us:
            <a href="https://facebook.com" target="_blank" rel="noopener" aria-label="Visit our Facebook page 
                    (opens in a new tab)"><i class="fab fa-facebook-square mx-1"></i></a>
            <a href="https://twitter.com" target="_blank" rel="noopener" aria-label="Visit our Twitter page 
                    (opens in a new tab)"><i class="fab fa-twitter-square mx-1"></i></a>
            <a href="https://instagram.com" target="_blank" rel="noopener" aria-label="Visit our Instagram page 
                    (opens in a new tab)"><i class="fab fa-instagram-square mx-1"></i></a>
        </p>

    </footer>
    <script>
        setTimeout(function () {
            let messages = document.getElementById("msg");
            if (messages) {
                let alert = new bootstrap.Alert(messages);
                alert.close();
            }
        }, 1600)
    </script>
</body>

</html>

templates/decline.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>The Tipsy Tiger Cocktail Guide</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">


</head>

<body class="screen">
    <div class="container-fluid hero-container ">
        <div class="col-lg-8 col-md-10 mx-auto">
            <!-- <img src="https://res.cloudinary.com/ddgxxa2hy/image/upload/v1659639221/My_project-1_13_d3yuaj.png"
                            class="logo col-lg-8 col-md-10 mx-auto" alt=""> -->
            <div class="text-center col-lg-8 col-md-10 mx-auto age-form">
                <h1 class="intro">OOPSY! Your not old enough.</h1>
                <h1 class="intro2"> You must be Over 18 to Enter</h1>
                <h1 class="intro2">The Tipsy Tiger Cocktail Guide</h1>
                <a href="{% url 'main' %}" class="btn-light btn-lg return"> Return to main page!</a>
            </div>
        </div>
    </div>

</body>

</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<header>

    <div class="container-fluid bg-image ">
        <div class="row hero-overlay hero-image img-fluid">
            <div class="col-12 hero-text text-center">
                <h1> Welcome to The Tipsy Tiger Cocktail Guide</h1>

            </div>
        </div>
    </div>

</header>

<div class="container-fluid">
    <hr>
    <div class="row">
        <div class="col-12">
            <h2 class="popular"><strong> Most popular cocktails<i class="fas fa-cocktail"></i></strong> <br>
                Head to <a class="recipe-link" href="{% url 'recipes' %}"> Cocktails</a> view more delicious recipes.
            </h2>
        </div>
    </div>

    <!-- Recipe Entries Column -->
    <div class="album py-5 bg-light">
        <div class="row">
            <!-- Recipe Snapshot Column -->
            <div class="col-12 mt-3 left">
                <div class="row">
                    {% for recipe in recipe_list %}
                    <div class="col-lg-4">
                        <div class="card mb-4">
                            <div class="card-body">
                                <div class="image-container">
                                    {% if 'placeholder' in recipe.recipe_image.url %}
                                    <img class="card-img-top"
                                        src="https://res.cloudinary.com/ddgxxa2hy/image/upload/v1661630412/yh7v8u7ajreg2fn3xcmu.png"
                                        alt="orange cocktail in small glass">
                                    {% else %}
                                    <img class="card-img-top" src=" {{ recipe.recipe_image.url }} "
                                        alt="{{ recipe.title }}">
                                    {% endif %}
                                    <div>
                                        <p class="recipe-type text-center"> {{ recipe.skill }} / {{ recipe.base}}</p>
                                        <h3 class="recipe-title home-cd"> {{ recipe.title }}</h3>
                                        <p class="recipe-footer card-footer">added by {{ recipe.author }} on
                                            {{ recipe.created_on}}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% if forloop.counter|divisibleby:3 %}
                    <!--</div>-->
                    <div class="row">
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid join-us">
        <div class="row col-lg-8 col-md-10 mx-auto">
            <h1>Join Us!</h1>
            <p class="heading">You can't buy happiness, but you can prepare a cocktail...</p>
            <p class="heading">Choose from our range of tried, tested & loved cocktails</p>
            <p class="heading">Even add you own personal favourites</p>
            {% if user.is_authenticated %}
            <p><a href="{% url 'account_signup' %}" class="btn btn-lg btn-secondary">Register</a></p>
            {% else %}
            <p><a href="{% url 'account_signup' %}" class="btn btn-lg btn-secondary">Register</a></p>
            {% endif %}
        </div>
    </div>
</div>


{% endblock %}

templates/main.html
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>The Tipsy Tiger Cocktail Guide</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body class="screen">

    <div class="container fluid ">
        <div class="text-center col-lg-8 col-md-10 mx-auto age-form">

            <h1 class="intro">Welcome to The Tipsy Tiger Cocktail Guide</h1>
            <h1 class="intro2">You need to be over 18!</h1>
            <h2 class="intro2">To visit this site</h2>

            <a href="{% url 'home' %}" class="check btn btn-primary btn-md">Yes I am over 18!</a>

            <a href="{% url 'decline' %}" class="uncheck  btn btn-primary btn-md">No I am under 18</a>
        </div>
    </div>

</body>

</html>

{% endblock %}

templates/recipes.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container fluid">
    <div class="row">
        <div class="col text-center recipes">
            <h1>Cocktail Recipes</h1>
            
        </div>
    </div>
    <!--Cocktail recipe filter-->
    <div class="row text-center">
        <form method="GET" class="recipe-filter">
            <p>Filter by</p>
            {{ RecipeFilter.form }}
            {% csrf_token %}
            <button class="btn btn-sm btn-secondary " type="submit" name="recipe_search" ><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>
<div class="row text-center like-intro">
    <h5>Why don't you give your favourite cocktails a cheers <i class="fas fa-glass-cheers"></i> The Tipsy Tiger version of a like.</h5>
    <h5>Or leave us a <i class="fas fa-comment"></i> comment let us know your thoughts.</h5>



</div>
<!--Recipe columns-->
<div class="row">
    <div class="col-12 mt-3 left">
        <div class="row">
            {% for recipe in recipe_list %}

            <div class="col-lg-4">
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="image-container">
                            {% if 'placeholder' in recipe.recipe_image.url %}
                            <img src="https://res.cloudinary.com/ddgxxa2hy/image/upload/v1661630412/yh7v8u7ajreg2fn3xcmu.png"
                                alt="orange cocktail in small glass">
                            {% else %}
                            <img class="card-image" src=" {{ recipe.recipe_image.url }}" alt="{{ recipe.title }}">
                            {% endif %}
                            <div class="card-info">
                                <p class="recipe-info"> {{ recipe.skill }} / {{ recipe.base }}</p>
                            </div>
                        </div>
                        <a class="recipe-title" href="{% url 'recipe_detail' recipe.slug %}">
                            <h3 class="recipe-title select"> {{ recipe.title }}</h3></a>

                        <hr>
                        <div>
                            <p class="card-footer"> Added by {{ recipe.author }} on {{ recipe.created_on }}</p>
                            <i class="fas fa-glass-cheers"> {{ recipe.number_of_cheers }} </i>

                            {% with comments.count as total_comments %}
                            <i class="fas fa-comment icon">{{ recipe.comments.count }}</i>
                            
                            {% endwith %}
                        </div>
                    </div>

                </div>

            </div>
            {% if forloop.counter|divisibleby:3 %}
        </div>
        <div class="row">
            {% endif %}
            {% empty %}
            <h3 class="empty text-center">Sorry this type of cocktail hasn't been added yet!</h3>
            <h3 class="empty2 text-center">Why not...</h3>
            {% endfor %}
        </div>
        
    </div>

</div>
<div class="row col-lg-2 col-md-3 mx-auto">
    <!-- <div class="col text-center"> -->
        <a class="btn btn-lg btn-secondary" href="{% url 'recipecreate' %}">Add A Cocktail</a>
    
</div>

{% endblock %}